version: '2.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
    - 2181:2181
    # volumes:
    # - "D:/docker/zookeeper/zoo1/data:/data"
    # - "D:/docker/zookeeper/zoo1/datalog:/datalog"

  kafka1:
    image: wurstmeister/kafka:2.11-2.0.1
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.31.132.5:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
    # volumes:
    # - D:/docker/kafka/kafka1/logs:/kafka
    depends_on:
      - zoo1